version: '3.8'

services:
  php:
    image: gek22/onlyphp-app:latest
    container_name: php-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: gek22/onlynginx-app:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
